export const options = {
  sizes: ['xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl'],
  weights: ['light', 'regular', 'medium', 'bold'],
  colors: [
    'neutral-120',
    'neutral-100',
    'neutral-80',
    'neutral-60',
    'neutral-40',
    'neutral-20',
    'neutral-00',
    'primary-main',
    'alert-success',
    'alert-error',
  ],
  alignments: ['left', 'center', 'right'],
  types: [
    'div',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'label',
    'legend',
    'p',
    'small',
    'span',
    'strong',
  ],
}
