export const options = {
  sizes: ['xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl'],
  weights: ['light', 'regular', 'medium', 'bold'],
  colors: [
    'neutral-00',
    'neutral-50',
    'neutral-100',
    'neutral-200',
    'neutral-300',
    'neutral-400',
    'neutral-500',
    'neutral-600',
    'neutral-700',
    'neutral-800',
    'neutral-900',
    'primary-main',
    'secondary-main',
    'alert-success',
    'alert-error',
  ],
  alignments: ['left', 'center', 'right'],
  transforms: ['capitalize', 'uppercase', 'lowercase', 'initial'],
  types: [
    'div',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'label',
    'legend',
    'p',
    'small',
    'span',
    'strong',
  ],
}
